### ISSUE TITLE
[Feature] RobCoin 2.0.0: Update Tracker

### ISSUE THREAD

**Issue by Ti1mmy** [STR-Coding-Club/RobCoin#3]
# RobCoin 2 - Decentralization

RobCoin was written to be an exercise to develop our knowledge and understanding in blockchain technology. As of version **1.x.x**, RobCoin is a functional cryptocurrency that employs cryptographic methods in the form of **private-public key cryptography** and **a proof of work algorithm** to advance and secure the blockchain, but fundamentally lacks the property of being decentralized. This means that the central ledger, the file that stores all of the transactions made on the blockchain, is stored on a single, centralized server and therefore contradicts the conventional interpretation that a cryptocurrency must be decentralized.

That's what RobCoin 2.0 aims to fix, among a list of other smaller features. Following through with our commitment to maintaining this project, St. Robert CHS Coding Club Alumni will be working to develop a hard fork of RobCoin that is decentralized.

***
This issue acts as a tracker for our progress towards a completed version of RobCoin 2.0.0.

- [ ] **Better Blockchain File** - `Store transactions in a more time/space-efficient file format`
- [ ] **Blockchain Verification** - `Create a 'Full Node' that independently validates the entire blockchain from the genesis block.`
- [ ] **Distributed Ledger** - `Implement a peer-to-peer network that distributes copies of the blockchain`
- [ ] **Proof of Work** - `Adjust the proof-of-work (mining) code to work with the decentralized code`
- [ ] . . . 

### QoL Fixes

- [ ] **Light Node + Wallet** - `Create a 'Light' wallet/node that does not need to store the entire blockchain`
- [ ] **Blockchain Explorer** - `Create a website to explore RobCoin's blockchain` - i.e: [https://etherscan.io/](https://etherscan.io/)
- [ ] More TBD
